spring.application.name=finance-control

server.port=9000

spring.datasource.url=jdbc:postgresql://localhost:5433/finance_control
spring.datasource.username=emanuel
spring.datasource.password=controller
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when_authorized

security.jwt.secret=RmluYW5jZUNvbnRyb2xBcGlKc29uV2ViVG9rZW5LZXlGb3JTdHVkeQ==
security.jwt.expiration-minutes=120

app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173

app.bootstrap-admin.enabled=true
app.bootstrap-admin.username=admin
app.bootstrap-admin.password=admin123
